# @formatter:off

[versions]

kotlin = "1.6.10"
jvm    = "11"

kafka  = "3.1.0"

kotlinx-serialization = "1.3.2"

###########
[libraries]
###########

kotlin-bom = { group = "org.jetbrains.kotlin", name = "kotlin-bom", version.ref = "kotlin" }

kafka-streams          = { group = "org.apache.kafka", name = "kafka-streams",            version.ref = "kafka" }
kafka-streamsTestUtils = { group = "org.apache.kafka", name = "kafka-streams-test-utils", version.ref = "kafka" }

kotlinx-serialization-bom  = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-bom", version.ref = "kotlinx-serialization" }
kotlinx-serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json" }
