name: Gradle Task
run-name: "Gradle Task ${{ inputs.gradle-task }} @ ${{ inputs.runs-on }}"

# Reusable Workflow for running a Gradle task

on:
  workflow_dispatch:

  workflow_call:
    inputs:
      gradle-task:
        description: "The Gradle task to run, including any flags"
        required: true
        type: string
      runs-on:
        description: "OSes to run the task on"
        required: true
        type: string
      github-environment:
        description: "GitHub Environment"
        required: false
        type: string
    secrets:
      SONATYPE_SIGNING_KEY_ID:
        description: Sonatype signing key ID
        required: false
      SONATYPE_SIGNING_KEY:
        description: Sonatype signing key
        required: false
      SONATYPE_SIGNING_PASSWORD:
        description: Sonatype signing password
        required: false
      SONATYPE_REPO_USERNAME:
        description: Sonatype repository password
        required: false
      SONATYPE_REPO_PASSWORD:
        description: Sonatype repository password
        required: false


concurrency:
  # note: the Workflow inputs are also included in the concurrency group
  group: "${{ github.workflow }} ${{ join(inputs.*) }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true


permissions:
  contents: read


jobs:

  run-task:
    runs-on: ${{ inputs.runs-on }}
    name: "./gradlew ${{ inputs.gradle-task}} @ ${{ inputs.runs-on }}"
    timeout-minutes: 60
    environment: ${{ inputs.github-environment }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true

      - name: Run ${{ inputs.gradle-task }}
        run: >-
          ./gradlew ${{ inputs.gradle-task }}
        env:
          ORG_GRADLE_PROJECT_signing.keyId: ${{ secrets.SONATYPE_SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signing.key: ${{ secrets.SONATYPE_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signing.password: ${{ secrets.SONATYPE_SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_sonatypeRepositoryUsername: ${{ SONATYPE_REPO_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypeRepositoryPassword: ${{ SONATYPE_REPO_PASSWORD }}

      - name: Upload build reports
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: build-report-${{ runner.os }}-${{ github.action }}
          path: "**/build/reports/"
          if-no-files-found: ignore
