name: Publish Maven Publications

on:
  workflow_dispatch:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    branches:
      - main

concurrency:
  group: "Maven Publishing on ${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  publish:
    needs: tests
    uses: ./.github/workflows/gradle_task.yml
    with:
      runs-on: ubuntu-latest
      gradle-task: >-
        publishAllPublicationsToSonatypeRepository
        --no-parallel
        --no-configuration-cache
      github-environment: sonatype-publish
    secrets:
      SONATYPE_SIGNING_KEY_ID: ${{ secrets.SONATYPE_SIGNING_KEY_ID }}
      SONATYPE_SIGNING_KEY: ${{ secrets.SONATYPE_SIGNING_KEY }}
      SONATYPE_SIGNING_PASSWORD: ${{ secrets.SONATYPE_SIGNING_PASSWORD }}
