name: Publish Maven

on:
  workflow_dispatch:
    inputs:
      checkout-ref:
        description: "The repository reference to checkout"
        required: false
        type: string
  workflow_call:
    inputs:
      checkout-ref:
        description: "The repository reference to checkout"
        required: false
        type: string


concurrency:
  group: "Publish Maven: ${{ github.workflow }}"
  cancel-in-progress: false


permissions:
  contents: write
  packages: write
  checks: write


jobs:

  sonatype-release:
    permissions:
      contents: read
      packages: write
      checks: write
    uses: ./.github/workflows/run_gradle_task.yml
    secrets: inherit
    with:
      runs-on: ubuntu-latest
      gradle-task: >-
        publishAllPublicationsToSonatypeRepository
        --stacktrace
        --no-configuration-cache
        --no-parallel
      checkout-ref: ${{ inputs.checkout-ref || github.event.repository.default_branch }}


  github-packages-release:
    permissions:
      contents: read
      packages: write
      checks: write
    uses: ./.github/workflows/run_gradle_task.yml
    with:
      runs-on: ubuntu-latest
      gradle-task: >-
        publishAllPublicationsToGitHubPackagesRepository
        --stacktrace
        --no-configuration-cache
        --no-parallel
      checkout-ref: ${{ inputs.checkout-ref || github.event.repository.default_branch }}
